from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer, Table, TableStyle

ORANGE = colors.HexColor("#ff5a1f")
INK = colors.HexColor("#161616")
MUTED = colors.HexColor("#6d6d6d")
PANEL = colors.HexColor("#f3f3f1")


@dataclass(frozen=True, slots=True)
class TranscriptMessage:
    author: str
    author_id: int
    created_at: datetime
    content: str
    attachments: tuple[str, ...] = ()
    is_bot: bool = False


def _pdf_text(value: str) -> str:
    return escape(value.encode("cp1252", errors="replace").decode("cp1252")).replace("\n", "<br/>")


def build_ticket_transcript(
    *,
    reference: str,
    subject: str,
    category: str,
    requester: str,
    opened_at: datetime,
    closed_by: str,
    messages: Iterable[TranscriptMessage],
    generated_at: datetime | None = None,
) -> tuple[bytes, int]:
    generated = generated_at or datetime.now(timezone.utc)
    transcript_messages = list(messages)
    output = BytesIO()
    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "TranscriptTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=23,
        leading=27,
        textColor=INK,
        spaceAfter=4 * mm,
    )
    eyebrow = ParagraphStyle(
        "Eyebrow",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7,
        leading=9,
        tracking=1.2,
        textColor=ORANGE,
        spaceAfter=2 * mm,
    )
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontSize=9, leading=13, textColor=INK)
    meta = ParagraphStyle("Meta", parent=body, fontSize=7.5, leading=10, textColor=MUTED)
    empty = ParagraphStyle("Empty", parent=body, alignment=TA_CENTER, textColor=MUTED, spaceBefore=12 * mm)

    def page(canvas, document) -> None:  # type: ignore[no-untyped-def]
        canvas.saveState()
        width, height = A4
        canvas.setFillColor(INK)
        canvas.rect(0, height - 18 * mm, width, 18 * mm, stroke=0, fill=1)
        canvas.setFillColor(ORANGE)
        canvas.rect(0, height - 18 * mm, 3 * mm, 18 * mm, stroke=0, fill=1)
        canvas.setFont("Helvetica-BoldOblique", 12)
        canvas.setFillColor(colors.white)
        canvas.drawString(16 * mm, height - 11.5 * mm, "TruckerWorldMP")
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#bdbdbd"))
        canvas.drawRightString(width - 15 * mm, height - 11.5 * mm, f"SUPPORT TRANSCRIPT  /  {reference}")
        canvas.setStrokeColor(colors.HexColor("#dedede"))
        canvas.line(15 * mm, 14 * mm, width - 15 * mm, 14 * mm)
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(MUTED)
        canvas.drawString(15 * mm, 9 * mm, "Private support record - generated by TruckerWorldMP")
        canvas.drawRightString(width - 15 * mm, 9 * mm, f"Page {document.page}")
        canvas.restoreState()

    document = BaseDocTemplate(
        output,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=27 * mm,
        bottomMargin=20 * mm,
        title=f"{reference} - {subject}",
        author="TruckerWorldMP Support",
        subject="Discord support transcript",
    )
    frame = Frame(document.leftMargin, document.bottomMargin, document.width, document.height, id="transcript")
    document.addPageTemplates([PageTemplate(id="transcript-pages", frames=[frame], onPageEnd=page)])
    story: list[object] = [
        Paragraph("DISCORD SUPPORT RECORD", eyebrow),
        Paragraph(_pdf_text(subject), title),
        Table(
            [
                [Paragraph("REFERENCE", eyebrow), Paragraph("CATEGORY", eyebrow), Paragraph("REQUESTER", eyebrow)],
                [Paragraph(_pdf_text(reference), body), Paragraph(_pdf_text(category.title()), body), Paragraph(_pdf_text(requester), body)],
                [Paragraph("OPENED", eyebrow), Paragraph("CLOSED BY", eyebrow), Paragraph("GENERATED", eyebrow)],
                [
                    Paragraph(opened_at.astimezone(timezone.utc).strftime("%d %b %Y, %H:%M UTC"), body),
                    Paragraph(_pdf_text(closed_by), body),
                    Paragraph(generated.astimezone(timezone.utc).strftime("%d %b %Y, %H:%M UTC"), body),
                ],
            ],
            colWidths=[60 * mm, 55 * mm, 55 * mm],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), PANEL),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d7d7d4")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#ddddda")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4 * mm),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4 * mm),
                    ("TOPPADDING", (0, 0), (-1, -1), 2.5 * mm),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5 * mm),
                ]
            ),
        ),
        Spacer(1, 7 * mm),
        Paragraph(f"CONVERSATION  /  {len(transcript_messages)} MESSAGES", eyebrow),
    ]
    if not transcript_messages:
        story.append(Paragraph("No user messages were recorded in this Discord channel.", empty))
    for index, message in enumerate(transcript_messages, start=1):
        timestamp = message.created_at.astimezone(timezone.utc).strftime("%d %b %Y, %H:%M:%S UTC")
        author_label = f"{message.author}  ({message.author_id})" + ("  [BOT]" if message.is_bot else "")
        content = message.content.strip() or "[No text content]"
        attachment_text = "".join(f"<br/><font color='#6d6d6d'>Attachment: {_pdf_text(url)}</font>" for url in message.attachments)
        card = Table(
            [[Paragraph(f"<b>{_pdf_text(author_label)}</b><br/><font color='#6d6d6d'>#{index} - {timestamp}</font>", meta)], [Paragraph(f"{_pdf_text(content)}{attachment_text}", body)]],
            colWidths=[170 * mm],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e9e9e6")),
                    ("BACKGROUND", (0, 1), (-1, -1), PANEL),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d7d7d4")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4 * mm),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4 * mm),
                    ("TOPPADDING", (0, 0), (-1, -1), 2.5 * mm),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5 * mm),
                ]
            ),
        )
        story.extend([card, Spacer(1, 3 * mm)])
    document.build(story)
    return output.getvalue(), len(transcript_messages)
